name = "TinnitusReconstructor"
uuid = "998763c9-5807-4081-8b95-f32419d2af94"
authors = ["Alec Hoyland <alec.hoyland@posteo.net> and contributors"]
version = "0.1.0"

[deps]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
LibSndFile = "b13ce0c6-77b0-50c6-a2db-140568b8d1a5"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
JuliaFormatter = "1"
LibSndFile = "2"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
