name = "TinnitusReconstructor"
uuid = "998763c9-5807-4081-8b95-f32419d2af94"
authors = ["Alec Hoyland <alec.hoyland@posteo.net> and contributors"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
